# Generated by Django 2.1.7 on 2023-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230908_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
